"""
URL configuration for storage app.

This module defines URL patterns for:
- Authenticated file operations (via FileViewSet with Router)
- Public file access (via public link, no authentication required)
"""

from django.urls import include, path
from rest_framework.routers import DefaultRouter

from .views import (
    FileViewSet,
    PublicFileDownloadView,
    PublicFileView,
)

# Router for authenticated file operations
# Disable format suffixes to avoid 'drf_format_suffix' converter registration errors in tests
router = DefaultRouter()
router.register(r"files", FileViewSet, basename="file")
router.include_format_suffixes = False

urlpatterns = [
    # Authenticated file operations (CRUD + custom actions)
    # Generated by Router:
    #   GET    /api/storage/files/              -> list
    #   POST   /api/storage/files/              -> create
    #   GET    /api/storage/files/{id}/         -> retrieve
    #   PUT    /api/storage/files/{id}/         -> update
    #   PATCH  /api/storage/files/{id}/         -> partial_update
    #   DELETE /api/storage/files/{id}/         -> destroy
    #   POST   /api/storage/files/upload/       -> upload
    #   GET    /api/storage/files/{id}/download/ -> download
    #   PATCH  /api/storage/files/{id}/rename/  -> rename
    #   PATCH  /api/storage/files/{id}/comment/ -> comment
    path("", include(router.urls)),
    # Public file access (no authentication required)
    path("public/<str:public_link>/", PublicFileView.as_view(), name="public-file"),
    path(
        "public/<str:public_link>/download/",
        PublicFileDownloadView.as_view(),
        name="public-file-download",
    ),
]
