# Generated by Django 6.0.2 on 2026-02-16 12:44

import django.db.models.deletion
import storage.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=255, upload_to=storage.utils.generate_unique_path, verbose_name='Физический файл с уникальным именем')),
                ('original_name', models.CharField(max_length=255, verbose_name='Оригинальное имя')),
                ('size', models.BigIntegerField(default=0, verbose_name='Размер файла в байтах')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время загрузки')),
                ('last_downloaded', models.DateTimeField(blank=True, null=True, verbose_name='Дата последнего скачивания')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарии к файлу')),
                ('public_link', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Ключ публичной ссылки')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
                'db_table': 'storage_file',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['owner', '-uploaded_at'], name='storage_fil_owner_i_8197f7_idx'), models.Index(fields=['public_link'], name='storage_fil_public__6d0afa_idx')],
            },
        ),
    ]
