# Generated by Django 6.0.2 on 2026-03-03 14:41

import django.core.validators
import storage.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="file",
            field=models.FileField(
                max_length=255,
                upload_to=storage.utils.generate_unique_path,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Физический файл с уникальным именем",
            ),
        ),
    ]
