import { createSlice, type PayloadAction } from "@reduxjs/toolkit";

import type { ColorScheme, Theme } from "@/shared/types/theme";

import { loadThemeFromStorage } from "../api/themeStorage";
import { resolveTheme } from "../lib/resolveTheme";
import type { ThemeState } from "./types";

const initialState: ThemeState = {
  theme: loadThemeFromStorage(),
  resolvedTheme: resolveTheme(loadThemeFromStorage()),
};

/**
 * A Redux slice for managing the application's theme state.
 *
 * @example
 * ```ts
 * import { setTheme } from './themeSlice';
 * dispatch(setTheme('dark'));
 * ```
 */
export const themeSlice = createSlice({
  name: "theme",
  initialState,
  reducers: {
    /**
     * Updates the user-selected theme and recalculates the resolved theme.
     *
     * @param state - The current Redux state for theme.
     * @param action - A Redux action with a payload of type {@link Theme}.
     */
    setTheme: (state, action: PayloadAction<Theme>) => {
      state.theme = action.payload;
      state.resolvedTheme = resolveTheme(action.payload);
    },
    /**
     * Directly sets the resolved color scheme in the state.
     *
     * @param state - The current Redux state for theme.
     * @param action - A Redux action with a payload of type {@link ColorScheme}.
     */
    setResolvedTheme: (state, action: PayloadAction<ColorScheme>) => {
      state.resolvedTheme = action.payload;
    },
  },
});

/**
 * Action creators generated by Redux Toolkit for the theme slice.
 */
export const { setTheme, setResolvedTheme } = themeSlice.actions;

/**
 * The reducer function for the theme slice.
 */
export const themeReducer = themeSlice.reducer;
