# Generated by Django 6.0.2 on 2026-04-20 11:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='storage_limit',
            field=models.BigIntegerField(default=52428800, help_text='Максимальный объём файлов пользователя в байтах', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Лимит хранилища в байтах'),
        ),
    ]
